# config.yaml
hms:
  enabled: true
  url: "mssql+pyodbc:///?odbc_connect=DRIVER=ODBC Driver 17 for SQL Server;Server=ilegdb04;Database=HMS;Trusted_Connection=Yes;"
  include_schemas: ["*"] # or ["*"] for all
  exclude_schemas:
    [
      "INFORMATION_SCHEMA",
      "sys",
      "db_owner",
      "db_accessadmin",
      "db_securityadmin",
      "db_ddladmin",
      "db_backupoperator",
      "db_datareader",
      "db_datawriter",
      "db_denydatareader",
      "db_denydatawriter",
    ]

hms_dev:
  enabled: true
  url: "mssql+pyodbc:///?odbc_connect=DRIVER=ODBC Driver 17 for SQL Server;Server=ilegdev01;Database=HMS_Dev;Trusted_Connection=Yes;"
  include_schemas: ["*"] # or ["*"] for all
  exclude_schemas:
    [
      "INFORMATION_SCHEMA",
      "sys",
      "db_owner",
      "db_accessadmin",
      "db_securityadmin",
      "db_ddladmin",
      "db_backupoperator",
      "db_datareader",
      "db_datawriter",
      "db_denydatareader",
      "db_denydatawriter",
    ]

snowflake:
  enabled: true
  sqlserver_url: "mssql+pyodbc:///?odbc_connect=DRIVER=ODBC Driver 17 for SQL Server;Server=ilegdb04;Database=HMS;Trusted_Connection=Yes;"
  linked_server: "SNOWFLAKE" # Your actual linked server name
  database: "CT_ORSINI_RAW" # Your Snowflake database name
  include_schemas: ["*"]
  exclude_schemas: ["INFORMATION_SCHEMA"]
output:
  path: "./metadata_cache/metadata.json"

rx30_offline:
  enabled: true
  url: "mssql+pyodbc:///?odbc_connect=DRIVER=ODBC Driver 17 for SQL Server;Server=ilegdb01;Database=Rx30;Trusted_Connection=Yes;"
  include_schemas: ["dbo"] # or ["*"] for all
  exclude_schemas:
    [
      "INFORMATION_SCHEMA",
      "sys",
      "db_owner",
      "db_accessadmin",
      "db_securityadmin",
      "db_ddladmin",
      "db_backupoperator",
      "db_datareader",
      "db_datawriter",
      "db_denydatareader",
      "db_denydatawriter",
    ]

fastrack:
  enabled: true
  url: "mssql+pyodbc:///?odbc_connect=DRIVER=ODBC Driver 17 for SQL Server;Server=ilegdb01;Database=fstrkdb_1;Trusted_Connection=Yes;"
  include_schemas: ["dbo"] # or ["*"] for all
  exclude_schemas:
    [
      "INFORMATION_SCHEMA",
      "sys",
      "db_owner",
      "db_accessadmin",
      "db_securityadmin",
      "db_ddladmin",
      "db_backupoperator",
      "db_datareader",
      "db_datawriter",
      "db_denydatareader",
      "db_denydatawriter",
    ]
